// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// schema.prisma's `env("DATABASE_URL")` is resolved from the process
// environment directly, independent of this file's `datasource.url` below —
// so the fallback has to be set on process.env itself. This only affects the
// Prisma CLI (generate/validate/migrate/studio), never the app's own
// PrismaClient at runtime (lib/db.ts reads DATABASE_URL from the real
// environment). It lets `generate` and `validate` — which don't need a
// reachable database — run in CI without a DATABASE_URL secret.
if (!process.env.DATABASE_URL) {
	process.env.DATABASE_URL =
		"postgresql://placeholder:placeholder@localhost:5432/placeholder";
}

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
	},
	datasource: {
		url: process.env.DATABASE_URL,
	},
});
